kri/apps/participant/urls.py
"""URL configuration for participant application."""

from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'participant'

authurls = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
]

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^team/krai/$', views.krai, name='krai'),
    url(r'^team/krsbi-beroda/$', views.krsbi_beroda, name='krsbi-beroda'),
    url(r'^team/krsti/$', views.krsti, name='krsti'),
    url(r'^team/krpai/$', views.krpai, name='krpai'),

    url(r'^person/(?P<person_type>[\w-]+)/$', views.person, name='person'),

    url(r'^tiket/$', views.supporter, name='supporter'),
    url(r'^tiket/verifikasi/([0-9]+)/$', views.verify_supporter, name='verify-supporter'),

] + authurls

kri/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    url(r'^', include('kri.apps.kri.urls')),
    url(r'^attendance/', include('kri.apps.attendance.urls')),
    url(r'^peserta/', include('kri.apps.participant.urls')),
    url(r'^ksk/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kri/apps/participant/forms.py
from django.forms import ModelForm, HiddenInput, DateInput, DateTimeField, FileInput
from django.contrib.auth.models import User
from .models import Team, Person, Manager, Supporter


class RegistrationForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class ManagerForm(ModelForm):
    class Meta:
        model = Manager
        fields = ['name', 'phone', 'requested_university', 'student_card']

class TeamForm(ModelForm):
    """Team model Form for registration"""
    arrival_time = DateTimeField(widget=DateInput(format='%d/%m/%Y %H:%M',
                                                  attrs={'class': 'form-control arrival-time'}),
                                 input_formats=['%d/%m/%Y %H:%M'])

    class Meta:
        model = Team
        fields = ['name', 'arrival_time', 'transport']


class PersonForm(ModelForm):
    """Person model Form for registration"""
    birthday = DateTimeField(
        widget=DateInput(format='%d/%m/%Y', attrs={'class': 'form-control birthday'}),
        input_formats=['%d/%m/%Y'])

    class Meta:
        model = Person
        fields = ['name', 'type', 'instance_id', 'birthday', 'gender', 'phone',
                  'email', 'photo']
        widgets = {
            'type': HiddenInput(),
            'photo': FileInput()
        }

class SupporterForm(ModelForm):
    class Meta:
        model = Supporter
        fields = ['amount']

kri/apps/participant/views.py
from django.http import JsonResponse, Http404
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login as auth_login
from django.contrib.auth.models import User
from .decorators import has_access
from .forms import RegistrationForm, ManagerForm, TeamForm, PersonForm, SupporterForm
from .models import Team, Person, University, Manager, Supporter


def login(request):
    context = {
        'university': University.objects.filter(user=None)
    }

    if request.method == 'POST':
        if request.POST['action'] == 'register':
            form_registration = RegistrationForm(request.POST)
            form_manager = ManagerForm(request.POST, request.FILES)
            if form_registration.is_valid() and form_manager.is_valid():
                user = User.objects.create_user(request.POST['username'], request.POST['email'],
                                                request.POST['password'])
                user.is_active = False
                user.save()

                manager = form_manager.save(commit=False)
                manager.user = user
                manager.save()

                messages.success(request, "Pendaftaran Anda sedang diverifikasi oleh panitia. Selanjutnya Anda akan dihubungi oleh LO.")

            else:
                context['register_error'] = True

        elif request.POST['action'] == 'login':
            return auth_login(request, template_name='participant/login.html')


    if request.GET.get('next', False):
        context['next'] = request.GET['next']

    return render(request, 'participant/login.html', context)


@login_required
def index(request):
    return redirect('kri:index')

    teams = {}
    for t in Team.TEAM_DIVISION:
        try:
            teams[t[0]] = request.user.university.team(t[0])
        except Team.DoesNotExist:
            teams[t[0]] = None

    return render(request, 'participant/index.html', {
        'app': 'participant',
        'has_access': request.user.university.all_access(),
        'teams': teams,
    })


@login_required
@has_access('krai')
def krai(request):
    return division(request, division='krai', title='Kontes Robot ABU Indonesia')


@login_required
@has_access('krsbi_beroda')
def krsbi_beroda(request):
    return division(request, division='krsbi_beroda',
                    title='Kontes Robot Sepak Bola Beroda Indonesia')


@login_required
@has_access('krsti')
def krsti(request):
    return division(request, division='krsti', title='Kontes Robot Seni Tari Indonesia')


@login_required
@has_access('krpai')
def krpai(request):
    return division(request, division='krpai', title='Kontes Robot Pemadam Api Indonesia')


def division(request, **kwargs):
    """Handle request for Team creation"""
    return redirect('participant:supporter')

    try:
        instance = request.user.university.team(kwargs['division'])
    except Team.DoesNotExist:
        instance = None

    if request.method == 'POST':
        form_team = TeamForm(request.POST, instance=instance)

        response_data = {}
        if form_team.is_valid():
            team = form_team.save(commit=False)
            team.university = request.user.university
            team.division = kwargs['division']
            team.save()
            response_data['status'] = 'success'
            response_data['message'] = 'Informasi tim telah disimpan.'
            response_data['team_id'] = team.id

        else:
            response_data['status'] = 'error'
            response_data['message'] = 'Ada kesalahan dalam formulir Anda.'

        if request.is_ajax():
            return JsonResponse(response_data)
        else:
            getattr(messages, response_data['status'])(request, response_data['message'])

    else:
        form_team = TeamForm(instance=instance)

        members = {
            'core_member': [],
            'mechanics': [],
            'adviser': [],
        }
        if instance:
            for m in instance.persons.all():
                members[m.type].append(m)

    return render(request, 'participant/division.html', {
        'app': 'participant',
        'active': kwargs['division'],
        'title': kwargs['title'],
        'has_access': request.user.university.all_access(),
        'team': instance,
        'form_team': form_team,
        'members': members
    })


@login_required
def person(request, person_type):
    """Handle request on person creation

    The action will depend on the HTTP method:
        - POST: try to save the form to a Person
        - Get: render PersonForm

    Raises:
        - Http404: person_type is not in Person.PERSON_TYPE or request is not ajax

    """
    if not person_type in ('core_member', 'mechanics', 'adviser') or not request.is_ajax():
        raise Http404

    if request.method == 'POST':
        return person_form_submission(request, person_type)
    else:
        return render_person_form(request, person_type)


def person_form_submission(request, person_type):
    """Handle PersonForm submission from request"""
    instance = get_person(request.POST['person_id'])
    member = save_person(request, person_type, instance)

    response_data = {}
    if member:
        response_data['person_id'] = member.id
        response_data['status'] = 'success'

        if member.photo:
            response_data['photo'] = member.photo.url

        if instance:
            response_data['message'] = Person.person_type_display(person_type) + ' berhasil diubah.'
        else:
            response_data['message'] = Person.person_type_display(person_type) + ' berhasil ditambahkan.'

    else:
        response_data['status'] = 'error'
        response_data['message'] = 'Gagal menambahkan ' + Person.person_type_display(person_type)

    return JsonResponse(response_data)


def get_person(person_id):
    """Try to get a Person from given person id"""
    try:
        if person_id != '':
            instance = Person.objects.get(pk=person_id)
        else:
            instance = None
    except (Person.DoesNotExist, IndexError):
        instance = None

    return instance


def save_person(request, person_type, instance):
    """Submit PersonForm from request"""
    member = None
    form_person = PersonForm(request.POST, request.FILES, instance=instance)

    if form_person.is_valid():
        member = form_person.save(commit=False)
        member.team = Team.objects.get(pk=request.POST['team_id'])
        member.type = person_type
        member.save()
    else:
        print(form_person.errors)

    return member


def render_person_form(request, person_type):
    """Render PersonForm with detailed context"""
    team = Team.objects.get(pk=request.GET['team_id'])
    available_slot = team.available_slot(person_type)
    if available_slot:
        return render(request, 'participant/person-form-panel.html', {
            'form': PersonForm(),
            'team_id': team.id,
            'person_type': person_type,
            'person_type_display': Person.person_type_display(person_type),
            'person_type_count': getattr(team, person_type)().count() + 1,
        })
    else:
        return JsonResponse({
            'status': 'error',
            'message': Person.person_type_display(person_type) + ' sudah penuh.'
        })


@login_required
def supporter(request):
    return redirect('kri:index')

    if request.method == 'POST':
        form = SupporterForm(request.POST)
        ticket = Supporter.order(form, request.user)

        if ticket is None:
            messages.error(
                request,
                'Pembelian Anda gagal karena melebihi kuota. Silahkan kurangi jumlah tiket.'
            )

    else:
        form = SupporterForm()

    ticket_left = Supporter.tickets_left()
    if ticket_left > 0:
        can_order = True
        ticket_ordered = Supporter.ticket_ordered(request.user)
        messages.info(
            request,
            'Harga tiket Rp. 25.000. Anda telah membeli {0} dari maksimal {1} tiket.'.format(
                ticket_ordered, Supporter.max_supporter(request.user.university)))

        ticket_left = Supporter.tickets_left(request.user)
        if ticket_left <= 0:
            can_order = False

    else:
        can_order = False
        messages.error(request, 'Tiket supporter telah habis.')

    if Supporter.ticket_ordered(request.user) > 0:
        price_due = Supporter.price_due(request.user)
        if price_due > 0:
            messages.error(
                request,
                ('Anda belum membayar {0} tiket sebesar Rp. {1}. '
                 'Silahkan transfer ke rekening Bank BCA 0373784513 a/n Falanas Farhan '
                 'maksimal 24 jam sejak pembelian. '
                 'Konfirmasi pembayaran dengan mengirim bukti transfer ke '
                 'kri2017@ugm.ac.id.').format(int(price_due/25000), price_due))
        else:
            messages.success(
                request,
                ('Tiket Anda sudah dibayar. '
                 'Tiket dapat ditukar saat pendaftaran ulang dengan menunjukkan '
                 'kartu mahasiswa Anda ({0}).').format(request.user.manager.name)
            )
    else:
        messages.warning(
            request,
            'Pembayaran dilakukan dengan transfer ke rekening Bank BCA dalam waktu 24 jam.'
        )


    return render(request, 'participant/ticket-buy.html', {
        'app': 'participant',
        'active': 'supporter',
        'title': 'Supporter',
        'can_order': can_order,
        'form': form,
        'ticket_left': ticket_left
    })


@login_required
def verify_supporter(request, ticket_id):
    """Verify ticket order given it's id"""
    if not request.user.has_perm('participant.change_supporter'):
        raise Http404

    Supporter.verify(ticket_id)

    messages.success(request, 'Tiket #{0} telah diverifikasi'.format(ticket_id))

kri/apps/participant/templates/participant/division-nav.html
<div class="row">
    {% if has_access.krai %}
    <div class="col-sm-6 col-md-3">
        <a href="{% url 'participant:krai' %}" class="btn btn-sm {% if not active == 'krai' %} btn-outline-clr {% endif %} btn-block">KRAI</a>
    </div>
    {% endif %}
    {% if has_access.krsbi_beroda %}
    <div class="col-sm-6 col-md-3">
        <a href="{% url 'participant:krsbi-beroda' %}" class="btn btn-sm {% if not active == 'krsbi_beroda' %} btn-outline-clr {% endif %} btn-block">KRSBI</a>
    </div>
    {% endif %}
    {% if has_access.krsti %}
    <div class="col-sm-6 col-md-3">
        <a href="{% url 'participant:krsti' %}" class="btn btn-sm {% if not active == 'krsti' %} btn-outline-clr {% endif %} btn-block">KRSTI</a>
    </div>
    {% endif %}
    {% if has_access.krpai %}
    <div class="col-sm-6 col-md-3">
        <a href="{% url 'participant:krpai' %}" class="btn btn-sm {% if not active == 'krpai' %} btn-outline-clr {% endif %} btn-block">KRPAI</a>
    </div>
    {% endif %}
</div>

kri/apps/participant/templates/participant/division.html
{% extends 'base.html' %}

{% load staticfiles participant %}

{% block page-style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/vendor/bootstrap-datetimepicker.min.css' %}" />
{% endblock %}]

{% block inline-style %}
{{ block.super }}
<style>
    .division-nav-back {
        margin-top: 10px;
    }
    h5 {
        margin-bottom: 25px;
    }

    #team-members {
        margin-top: 70px;
    }

    .panel-group-alt .form-group {
        line-height: 23.4375px;
    }

    .panel-group-alt input {
        line-height: 35px;
        margin-bottom: 15px !important;
    }

    .panel-body button {
        margin-bottom: 20px !important;
    }

    select {
        border: 1px solid #e9e9e9;
    }

    .bootstrap-datetimepicker-widget a[data-action] {
        min-width: 0;
        min-height: 0;
        background-color: #fff;
        color: #FF9800;
        margin: 0;
        padding: 0;
    }
</style>
{% endblock inline-style %}

{% block content %}
{% include 'header.html' %}

<div class="section-peserta container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            {% include 'participant/division-nav.html' %}
            <div class="division-nav-back">
                <a href="{% url 'participant:index' %}"><span class="fa fa-angle-left"></span> Kembali</a>
            </div>
            <h5 style="margin-top: 30px;">
                <span class="highlight">{% block team-title %}{{ title }}{% endblock %}</span>
            </h5>
            <form id="form-team" action="{% block form-action-team %}{% endblock %}" method="post" enctype="multipart/form-data">
                {% include 'message.html' %}
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">Nama Tim</label>
                    {{ form_team.name }}
                    {{ form_team.name.errors }}
                </div>
                <div class="form-group">
                    <label for="arrival_time">Waktu Kedatangan</label>
                    {{ form_team.arrival_time }}
                    {{ form_team.arrival_time.errors }}
                </div>
                <div class="form-group">
                    <label for="transport">Transportasi</label>
                    {{ form_team.transport }}
                    {{ form_team.transport.errors }}
                </div>
                <div class="form-group align-right">
                    <button type="submit" class="btn btn-sm">Simpan</button>
                </div>
            </form>

            <div id="team-members" class="tabs-wrapper tabs-horizontal" {% if not team %}style="display: none;"{% endif %}>
                <div class="nav-wrapper">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#tab-core-member" data-toggle="tab"><span class="fa fa-group"></span> Tim Inti</a></li>
                        <li><a href="#tab-mechanics" data-toggle="tab"><span class="fa fa-gear"></span> Mekanik</a></li>
                        <li><a href="#tab-adviser" data-toggle="tab"><span class="fa fa-user"></span> Dosen Pembimbing</a></li>
                    </ul>
                </div>
                
                <div class="tab-content">
                    <div id="tab-core-member" class="tab-pane active in fade">
                        <div class="row">
                            <div class="col-sm-10 col-sm-offset-1">
                                <div id="core_member_persons" class="panel-group panel-group-alt">
                                    {% for person in members.core_member %}
                                    {% person_form_panel person forloop.counter %}
                                    {% endfor %}
                                </div>
                                <div class="align-center">
                                    <form action="{% url 'participant:person' 'core_member' %}" method="GET" class="person-request">
                                        <input type="hidden" name="team_id" value="{{ team.id }}">
                                        <button type="submit" class="btn btn-sm" name="person_type" value="core_member">Tambah Tim Inti</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="tab-mechanics" class="tab-pane fade">
                        <div class="row">
                            <div class="col-sm-10 col-sm-offset-1">
                                <div id="mechanics_persons" class="panel-group panel-group-alt">
                                    {% for person in members.mechanics %}
                                    {% person_form_panel person forloop.counter %}
                                    {% endfor %}
                                </div>
                                <div class="align-center">
                                    <form action="{% url 'participant:person' 'mechanics' %}" method="GET" class="person-request">
                                        <input type="hidden" name="team_id" value="{{ team.id }}">    
                                        <button type="submit" class="btn btn-sm" name="person_type" value="mechanics">Tambah Mekanik</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="tab-adviser" class="tab-pane fade">
                        <div class="row">
                            <div class="col-sm-10 col-sm-offset-1">
                                <div id="adviser_persons" class="panel-group panel-group-alt">
                                    {% for person in members.adviser %}
                                    {% person_form_panel person forloop.counter %}
                                    {% endfor %}
                                </div>
                                <div class="align-center">
                                    <form action="{% url 'participant:person' 'adviser' %}" method="GET" class="person-request">
                                        <input type="hidden" name="team_id" value="{{ team.id }}">
                                        <button type="submit" class="btn btn-sm" name="person_type" value="adviser">Tambah Dosen Pembimbing</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block inline-script %}
<script type="text/javascript" src="{% static 'js/moment.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
<script type="text/javascript">
    var dateTimePickerIcons = {
        time: 'fa fa-clock-o',
        date: 'fa fa-calendar',
        up: 'fa fa-arrow-up',
        down: 'fa fa-arrow-down',
        previous: 'fa fa-arrow-left',
        next: 'fa fa-arrow-right',
        today: 'glyphicon glyphicon-screenshot',
        clear: 'glyphicon glyphicon-trash',
        close: 'glyphicon glyphicon-remove'
    }
    $(function () {

        $('.arrival-time').datetimepicker({
            format: 'DD/MM/YYYY HH:mm',
            defaultDate: '05/11/2017 09:00',
            stepping: 5,
            sideBySide: true,
            icons: dateTimePickerIcons,
        });

        $('.birthday').datetimepicker({
            format: 'DD/MM/YYYY',
            icons: dateTimePickerIcons,
            widgetPositioning: {
                horizontal: 'auto',
                vertical: 'top'
            },
            viewMode: 'years'
        });
    });
</script>
{% endblock %}

kri/apps/participant/templates/participant/index.html
{% extends 'base.html' %}

{% block inline-style %}
{{ block.super }}
<style>
    .team-overview {
        margin: 20px 0;
    }
</style>
{% endblock inline-style %}

{% block content %}
{% include 'header.html' %}

<div class="section-peserta container">
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
            {% include 'participant/division-nav.html' %}
            <h5 style="margin-top: 30px;">
                <span class="highlight">{{ user.university.name }}</span>
            </h5>
            <div class="row">
                {% if has_access.krai %}
                <div class="col-md-6">
                    <div class="team-overview">
                        <h6>Kontes Robot ABU Indonesia <small><a href="{% url 'participant:krai' %}"><span class="fa fa-edit"></span></a></small></h6>
                        <div class="row">
                            <div class="col-xs-8">Nama tim:</div>
                            <div class="col-xs-4">{{ teams.krai.name|default:'-' }}</div>
                        </div>
                        <div class="row">
                            <div class="col-xs-8">Tim Inti:</div>
                            <div class="col-xs-4">{% if teams.krai %}{{ teams.krai.core_member.count }} / {{ teams.krai.max_core_member }}{% else %} - {% endif %}</div>
                        </div>
                        <div class="row">
                            <div class="col-xs-8">Mekanik:</div>
                            <div class="col-xs-4">{% if teams.krai %}{{ teams.krai.mechanics.count }} / {{ teams.krai.max_mechanics }}{% else %} - {% endif %}</div>
                        </div>
                        <div class="row">
                            <div class="col-xs-8">Dosen Pembimbing:</div>
                            <div class="col-xs-4">{% if teams.krai %}{{ teams.krai.adviser.count }} / {{ teams.krai.max_adviser }}{% else %} - {% endif %}</div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% if has_access.krsbi_beroda %}
                <div class="col-md-6">
                    <div class="team-overview">
                        <h6>Kontes Robot Sepak Bola Beroda Indonesia <small><a href="{% url 'participant:krsbi-beroda' %}"><span class="fa fa-edit"></span></a></small></h6>
                        <div class="row">
                            <div class="col-xs-8">Nama tim:</div>
                            <div class="col-xs-4">{{ teams.krsbi_beroda.name|default:'-' }}</div>
                        </div>
                        <div class="row">
                            <div class="col-xs-8">Tim Inti:</div>
                            <div class="col-xs-4">{% if teams.krsbi_beroda %}{{ teams.krsbi_beroda.core_member.count }} / {{ teams.krsbi_beroda.max_core_member }}{% else %} - {% endif %}</div>
                        </div>
                        <div class="row">
                            <div class="col-xs-8">Mekanik:</div>
                            <div class="col-xs-4">{% if teams.krsbi_beroda %}{{ teams.krsbi_beroda.mechanics.count }} / {{ teams.krsbi_beroda.max_mechanics }}{% else %} - {% endif %}</div>
                        </div>
                        <div class="row">
                            <div class="col-xs-8">Dosen Pembimbing:</div>
                            <div class="col-xs-4">{% if teams.krsbi_beroda %}{{ teams.krsbi_beroda.adviser.count }} / {{ teams.krsbi_beroda.max_adviser }}{% else %} - {% endif %}</div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% if has_access.krsti %}
                <div class="col-md-6">
                    <div class="team-overview">
                        <h6>Kontes Robot Seni Tari Indonesia <small><a href="{% url 'participant:krsti' %}"><span class="fa fa-edit"></span></a></small></h6>
                        <div class="row">
                            <div class="col-xs-8">Nama tim:</div>
                            <div class="col-xs-4">{{ teams.krsti.name|default:'-' }}</div>
                        </div>
                        <div class="row">
                            <div class="col-xs-8">Tim Inti:</div>
                            <div class="col-xs-4">{% if teams.krsti %}{{ teams.krsti.core_member.count }} / {{ teams.krsti.max_core_member }}{% else %} - {% endif %}</div>
                        </div>
                        <div class="row">
                            <div class="col-xs-8">Mekanik:</div>
                            <div class="col-xs-4">{% if teams.krsti %}{{ teams.krsti.mechanics.count }} / {{ teams.krsti.max_mechanics }}{% else %} - {% endif %}</div>
                        </div>
                        <div class="row">
                            <div class="col-xs-8">Dosen Pembimbing:</div>
                            <div class="col-xs-4">{% if teams.krsti %}{{ teams.krsti.adviser.count }} / {{ teams.krsti.max_adviser }}{% else %} - {% endif %}</div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% if has_access.krpai %}
                <div class="col-md-6">
                    <div class="team-overview">
                        <h6>Kontes Robot Pemadam Api Indonesia <small><a href="{% url 'participant:krpai' %}"><span class="fa fa-edit"></span></a></small></h6>
                        <div class="row">
                            <div class="col-xs-8">Nama tim:</div>
                            <div class="col-xs-4">{{ teams.krpai.name|default:'-' }}</div>
                        </div>
                        <div class="row">
                            <div class="col-xs-8">Tim Inti:</div>
                            <div class="col-xs-4">{% if teams.krpai %}{{ teams.krpai.core_member.count }} / {{ teams.krpai.max_core_member }}{% else %} - {% endif %}</div>
                        </div>
                        <div class="row">
                            <div class="col-xs-8">Mekanik:</div>
                            <div class="col-xs-4">{% if teams.krpai %}{{ teams.krpai.mechanics.count }} / {{ teams.krpai.max_mechanics }}{% else %} - {% endif %}</div>
                        </div>
                        <div class="row">
                            <div class="col-xs-8">Dosen Pembimbing:</div>
                            <div class="col-xs-4">{% if teams.krpai %}{{ teams.krpai.adviser.count }} / {{ teams.krpai.max_adviser }}{% else %} - {% endif %}</div>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

kri/apps/participant/templates/participant/login.html
{% extends 'base.html' %}

{% block inline-style %}
{{ block.super }}
<style>
.form-login .password-reset {
    padding-bottom: 12px;
}

.form-box {
    border: 1px solid #e9e9e9;
    padding: 30px 20px 40px;
    margin: 40px 0 100px;
}

.form-group {
    margin-bottom: 0;
}

ul {
    list-style: circle inside;
}

li {
    list-style: circle inside;
    margin: 0;
}

@media (min-width: 768px) {
    .form-login .action {
        margin-top: 15px;
    }

    .form-login .password-reset {
        padding-top: 12px;
    }
}

@media (max-width: 767px) {
    .form-box {
        margin: 0 0 60px;
    }
    .form-login .btn {
        width: 100%;
    }
}
</style>
{% endblock inline-style %}

{% block content %}
{% include 'header.html' %}

<div class="container">
    <div class="row">
        <div class="col-md-12 col-lg-8 col-lg-offset-2">
            <div class="alert alert-info" style="margin-bottom: 100px;">
                <p><strong>Pembelian Tiket Supporter</strong></p>
                <ul>
                    <li>Periode Pre Order sudah habis, silahkan membeli tiken On The Spot</li>
                    <li>Harga tiket Rp. 25.000,-.</li>
                </ul>
            </div>
            {% include 'message.html' %}
        </div>
    </div>
    {% comment %}
    <div class="row">
        <div class="col-md-6 col-lg-4 col-md-offset-3 col-lg-offset-4">
            <div class="form-box">
                <h5 class="align-center" style="margin-bottom: 25px;">
                    <span class="highlight">Login</span>
                </h5>
                {% if form.errors %}
                <div class="alert alert-warning">
                    Username dan password tidak cocok atau akun anda belum diverifikasi.
                </div>
                {% endif %}
                <form action="{% url 'participant:login' %}" method="post" class="form-login disable-ajax-form" novalidate>
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" name="username" required aria-required="true" placeholder="Username" autofocus>
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" required aria-required="true" placeholder="Password">
                    </div>
                    <div class="row action">
                        <div class="col-sm-6 password-reset">
                            {% comment %}<a href="{% url 'password_reset' %}">Lupa Password?</a>{% endcomment %}
                        {% comment %}
                        </div>
                        <div class="col-sm-6 align-right">
                            <button class="btn" type="submit" name="action" value="login">Login</button>
                        </div>
                    </div>
                    <input type="hidden" name="next" value="{{ next }}" />
                </form>
            </div>
        </div>
    </div>
    {% endcomment %}
</div>

{% endblock content %}